ALTER TABLE products MODIFY COLUMN price BIGINT NOT NULL;
ALTER TABLE cart_detail MODIFY COLUMN price BIGINT NOT NULL;
ALTER TABLE orders MODIFY COLUMN total_price BIGINT NOT NULL;
ALTER TABLE order_detail MODIFY COLUMN price BIGINT NOT NULL;
